# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: echo "Environment: ${{ inputs.environment }}"
      - name: Show secret
        run: echo "Secret is set"
